app/Directory.Build.props

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Update AzureIdentitySDK client

---

infra/core/ai/cognitiveservices.bicep
infra/main.bicep

The cognitive services API changed.  We need this update to support it.

Update cogservices to support new RP API

---

app/Dockerfile
app/backend/MinimalApi.csproj
infra/main.bicep

Switching the default model from davinci to turbo because davinci was depreciated on July 6th and you can no longer deploy with it. 
[ ] Yes
[X ] No
[X ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Update the gpt model from davinci to turbo

---

README.md

Changed the readme to use http for local usage so it works properly on DevContainers and Linux when there is not SSL cert on the machine. Also updated the readme to reflect the sample uses Turbo and not Davinci. 
[ ] Yes
[X ] No
[ ] Bugfix
[ ] Feature
[ X] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...

change from https to http and model update

---

app/backend/Extensions/WebApplicationExtensions.cs
app/backend/GlobalUsings.cs
app/frontend/Pages/Docs.razor.cs
app/functions/EmbedFunctions/EmbeddingFunction.cs
app/functions/EmbedFunctions/Services/EmbeddingAggregateService.cs
app/shared/Shared/Models/DocumentResponse.cs

Post-processing of uploaded blob from trigger:
- Once embedded (persist both of the following to the blob's metadata):
- Embedding type
- Processing status

Set the metadata for the blob, post-processing.

---

README.md
infra/main.bicep

Improve the readme for better clarification on the workflow. Also adding restrictions on the location in Bicep to prevent attempting to deploy to a region that doesn't support OpenAI.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```

Readme improvements

---

README.md
app/backend/MinimalApi.csproj
app/backend/Program.cs
infra/main.bicep
infra/main.parameters.json

* ...
Fix
#127 
#128 
#177 
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fix 127, 128, 177

---

app/backend/Program.cs
app/frontend/Pages/Docs.razor.cs
app/frontend/Services/ApiClient.cs
app/frontend/wwwroot/getCookie.js
app/frontend/wwwroot/index.html

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

add antiforgery header when uploading document

---

infra/main.bicep

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Add OpenAI function appsettings

---

app/prepdocs/PrepareDocs/Program.Clients.cs

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

fixing a bug for checking if to use Azure Open AI

---

app/frontend/Components/SettingsPanel.razor

Fixes #275
cc @mattleibow - this is the issue you saw earlier today

Fix SettingsPanel exception with RetrievalMode enum

---

README.md

Add the dotnet-maui product to the README metadata so that the sample shows up in the MAUI samples browser.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
```
cd [repo-name]
npm install
```
```
```
* ...

Include in MAUI samples browser

---

app/Directory.Build.props

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Update Directory.Build.props to remove semantic version

---

.github/workflows/azure-dev-validation.yml

* ...
partially fix #285 
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

add security-events write permission

---

app/Directory.Build.props
app/Directory.Packages.props

* ...
```
[ ] Yes
[ ] No
```
Fix #331
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

update azure identity package

---

README.md
app/Directory.Packages.props
app/backend/MinimalApi.csproj
infra/main.bicep

* ...
```
[ ] Yes
[ ] No
```
fix #333 
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

fix #333 and update sk version

---

app/Directory.Packages.props

* ...
```
[ ] Yes
[ ] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

update Azure.Identity package version to fix security vulnerability

---

README.md
SECURITY.md

Closes #337 pending adding topics to repo settings. 
@LittleLittleCloud

fix: fix validation issues

---

README.md

Update instances where Azure AI Search is referred to as Cognitive Search.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Refactoring (no functional changes, no api changes)
```

Update README.md with Azure AI Search

---

README.md

Add a video to describe and explain the process to deploy to Azure from a Codespace.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[X] Documentation content changes
```
```
cd [repo-name]
```
In bash or a console
```
azd up
```

Add video to explain the deploy from Codespaces

---

.github/workflows/stale-bot.yml

Add a GH Workflow that runs every day and close stale issues and PRs
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
*  Run the action

GH Workflow to Close stale issues and PRs
